# Generated by Django 2.1.15 on 2022-06-07 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='campana_publicitaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campana', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('objetivo_campana', models.CharField(blank=True, max_length=100, verbose_name='Objetivo')),
                ('publico_campana', models.CharField(blank=True, max_length=100, verbose_name='Publico')),
                ('presupuesto_campana', models.IntegerField(null=True, verbose_name='Presupuesto')),
                ('eficacia_camapana', models.CharField(blank=True, max_length=100, verbose_name='Eficacia')),
            ],
            options={
                'verbose_name': 'campana_publicitaria',
                'verbose_name_plural': 'campanas_publicitarias',
            },
        ),
        migrations.CreateModel(
            name='cuentas_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=60, null=True, verbose_name='Identificador')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='Username')),
                ('created_at', models.CharField(max_length=30, null=True, verbose_name='Creado en')),
                ('location', models.CharField(max_length=30, null=True, verbose_name='location')),
                ('followers_count', models.IntegerField(null=True, verbose_name='Followers count')),
                ('following_count', models.IntegerField(null=True, verbose_name='Following count')),
                ('post_count', models.IntegerField(null=True, verbose_name='Post count')),
                ('listed_count', models.IntegerField(null=True, verbose_name='Listed count')),
                ('fullname', models.CharField(max_length=30, null=True, verbose_name='Fullname')),
                ('profile_pic_url', models.CharField(max_length=500, null=True, verbose_name='Url foto perfil')),
                ('web_site', models.CharField(max_length=500, null=True, verbose_name='Url')),
                ('is_competition', models.BooleanField(default=False)),
                ('avg_compound', models.FloatField(default=0, null=True, verbose_name='AVG compouse')),
                ('data_red_campana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campana_publicitaria')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='data_red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion_id', models.CharField(max_length=30, null=True, verbose_name='Id')),
                ('publicacion_fecha', models.CharField(blank=True, max_length=60, null=True, verbose_name='Fecha')),
                ('publicacion_texto', models.TextField(null=True)),
                ('publicacion_likes', models.IntegerField(null=True, verbose_name='Likes')),
                ('publicacion_comentarios', models.IntegerField(null=True, verbose_name='Comentarios')),
                ('publicacion_compartidos', models.IntegerField(null=True, verbose_name='Veces compartido')),
                ('publicacion_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='User')),
                ('is_from_hashtag', models.BooleanField(default=False)),
                ('data_red_campana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campana_publicitaria')),
            ],
            options={
                'verbose_name': 'data_red',
                'verbose_name_plural': 'data_redes',
            },
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='escucha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escucha', models.CharField(blank=True, max_length=100, verbose_name='NombreEscucha')),
                ('usuario_red_social', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('fecha_inicio_red_social', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final_red_social', models.DateField(verbose_name='Fecha Final')),
                ('es_competencia', models.BooleanField()),
                ('campana_publicitaria_red_social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campana_publicitaria')),
            ],
            options={
                'verbose_name': 'escucha',
                'verbose_name_plural': 'Escuchas',
            },
        ),
        migrations.CreateModel(
            name='escucha_credencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_bearer_token', models.CharField(max_length=300, verbose_name='Bearer token')),
                ('instagram_username', models.CharField(max_length=50, verbose_name='Instagram username')),
                ('instagram_password', models.CharField(max_length=50, verbose_name='Instagram Password')),
                ('instagram_path', models.CharField(max_length=50, verbose_name='Instagram Path')),
            ],
            options={
                'verbose_name': 'escucha_credenciales',
                'verbose_name_plural': 'escuchas_credenciales',
            },
        ),
        migrations.CreateModel(
            name='estado_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_nombre_empresa', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'estado_empresa',
                'verbose_name_plural': 'estado_empresas',
            },
        ),
        migrations.CreateModel(
            name='hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hastag', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'hashtag',
                'verbose_name_plural': 'hashtags',
            },
        ),
        migrations.CreateModel(
            name='red_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red_social', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'red_social',
                'verbose_name_plural': 'redes_sociales',
            },
        ),
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='escucha',
            name='credenciales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.escucha_credencial'),
        ),
        migrations.AddField(
            model_name='escucha',
            name='empresa_red_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
        ),
        migrations.AddField(
            model_name='escucha',
            name='hashtag_red_social',
            field=models.ManyToManyField(to='app.hashtag'),
        ),
        migrations.AddField(
            model_name='escucha',
            name='red_social',
            field=models.ManyToManyField(to='app.red_social'),
        ),
        migrations.AddField(
            model_name='escucha',
            name='ubicacion_red_social',
            field=models.ManyToManyField(to='app.ubicacion'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estado_empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='data_red',
            name='data_red_escucha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.escucha'),
        ),
        migrations.AddField(
            model_name='data_red',
            name='data_red_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.red_social'),
        ),
        migrations.AddField(
            model_name='cuentas_empresa',
            name='data_red_escucha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.escucha'),
        ),
        migrations.AddField(
            model_name='cuentas_empresa',
            name='data_red_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.red_social'),
        ),
        migrations.AddField(
            model_name='campana_publicitaria',
            name='empresa_campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
        ),
        migrations.AddField(
            model_name='campana_publicitaria',
            name='ubicacion_campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ubicacion'),
        ),
        migrations.AddField(
            model_name='campana_publicitaria',
            name='usuario_campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
