# Generated by Django 2.1.15 on 2020-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion_id', models.IntegerField(null=True, unique=True, verbose_name='Id')),
                ('publicacion_fecha', models.DateTimeField(verbose_name='Fecha')),
                ('publicacion_texto', models.CharField(blank=True, max_length=60, verbose_name='Text')),
                ('publicacion_likes', models.IntegerField(null=True, verbose_name='Likes')),
                ('publicacion_comentarios', models.IntegerField(null=True, verbose_name='Comentarios')),
                ('publicacion_compartidos', models.IntegerField(null=True, verbose_name='Veces compartido')),
                ('publicacion_user', models.CharField(blank=True, max_length=30, verbose_name='User')),
            ],
            options={
                'verbose_name': 'data_red',
                'verbose_name_plural': 'data_redes',
            },
        ),
        migrations.AlterModelOptions(
            name='red_social',
            options={},
        ),
    ]
