# Generated by Django 2.1.15 on 2022-06-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas_empresa',
            name='data_red_campana',
        ),
        migrations.RemoveField(
            model_name='cuentas_empresa',
            name='data_red_escucha',
        ),
        migrations.RemoveField(
            model_name='cuentas_empresa',
            name='data_red_social',
        ),
        migrations.DeleteModel(
            name='cuentas_empresa',
        ),
    ]
