# Generated by Django 2.1.15 on 2020-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201006_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_red',
            name='publicacion_fecha',
            field=models.CharField(blank=True, max_length=60, verbose_name='Fecha'),
        ),
    ]
