# Generated by Django 2.1.15 on 2022-06-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220606_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=60, null=True, verbose_name='Identificador')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='Username')),
                ('created_at', models.CharField(max_length=30, null=True, verbose_name='Creado en')),
                ('location', models.CharField(max_length=30, null=True, verbose_name='location')),
                ('followers_count', models.IntegerField(null=True, verbose_name='Followers count')),
                ('following_count', models.IntegerField(null=True, verbose_name='Following count')),
                ('post_count', models.IntegerField(null=True, verbose_name='Post count')),
                ('listed_count', models.IntegerField(null=True, verbose_name='Listed count')),
                ('fullname', models.CharField(max_length=30, null=True, verbose_name='Fullname')),
                ('profile_pic_url', models.CharField(max_length=500, null=True, verbose_name='Url foto perfil')),
                ('web_site', models.CharField(max_length=500, null=True, verbose_name='Url')),
                ('is_competition', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
