# Generated by Django 2.1.15 on 2020-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201006_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_red',
            name='publicacion_id',
            field=models.CharField(max_length=30, null=True, verbose_name='Id'),
        ),
    ]
