# Generated by Django 2.1.15 on 2022-06-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cuentas_empresa_data_red_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_empresa',
            name='data_red_campana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campana_publicitaria'),
        ),
        migrations.AddField(
            model_name='cuentas_empresa',
            name='data_red_escucha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.escucha'),
        ),
    ]
