# Generated by Django 2.1.15 on 2020-10-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201006_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitter_credencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=100, verbose_name='App key')),
                ('secret_key', models.CharField(max_length=100, verbose_name='Secret key')),
                ('bearer_token', models.CharField(max_length=100, verbose_name='Bearer token')),
                ('access_token', models.CharField(max_length=100, verbose_name='Access token')),
                ('token_secret', models.CharField(max_length=100, verbose_name='Token secret')),
            ],
            options={
                'verbose_name': 'twitter_credential',
                'verbose_name_plural': 'twitter_credentials',
            },
        ),
        migrations.AddField(
            model_name='data_red',
            name='publicacion_red_social',
            field=models.CharField(blank=True, max_length=30, verbose_name='Red Social'),
        ),
    ]
