# Generated by Django 2.1.15 on 2020-10-14 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201007_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_red',
            name='publicacion_red_social',
        ),
        migrations.AddField(
            model_name='data_red',
            name='data_red_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.red_social'),
        ),
    ]
