# Generated by Django 2.1.15 on 2020-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201013_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_credencial',
            name='access_token',
            field=models.CharField(max_length=300, verbose_name='Access token'),
        ),
        migrations.AlterField(
            model_name='twitter_credencial',
            name='app_key',
            field=models.CharField(max_length=300, verbose_name='App key'),
        ),
        migrations.AlterField(
            model_name='twitter_credencial',
            name='bearer_token',
            field=models.CharField(max_length=300, verbose_name='Bearer token'),
        ),
        migrations.AlterField(
            model_name='twitter_credencial',
            name='secret_key',
            field=models.CharField(max_length=300, verbose_name='Secret key'),
        ),
        migrations.AlterField(
            model_name='twitter_credencial',
            name='token_secret',
            field=models.CharField(max_length=300, verbose_name='Token secret'),
        ),
    ]
