# Generated by Django 2.1.15 on 2022-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_cuentas_empresa_avg_compound'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_empresa',
            name='avg_compound',
            field=models.FloatField(default=0, null=True, verbose_name='AVG compouse'),
        ),
    ]
